### ISSUE TITLE
OSError: Netlink error: No such file or directory (2)

### ISSUE THREAD

**Issue by BrixSat** [mvneves/iotop-cgroups#1]
Running on a lxc container proxmox virtualized. 

Kernel Linux machine 4.15.18-9-pve #1 SMP PVE 4.15.18-30 (Thu, 15 Nov 2018 13:32:46 +0100) x86_64 x86_64 x86_64 GNU/Linux

# ./iotop.py 
Traceback (most recent call last):
  File "./iotop.py", line 12, in <module>
    main()
  File "/root/iotop-cgroups/iotop/ui.py", line 656, in main
    main_loop()
  File "/root/iotop-cgroups/iotop/ui.py", line 646, in <lambda>
    main_loop = lambda: run_iotop(options)
  File "/root/iotop-cgroups/iotop/ui.py", line 538, in run_iotop
    return curses.wrapper(run_iotop_window, options)
  File "/usr/lib64/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/root/iotop-cgroups/iotop/ui.py", line 527, in run_iotop_window
    taskstats_connection = TaskStatsNetlink(options)
  File "/root/iotop-cgroups/iotop/data.py", line 140, in __init__
    self.family_id = controller.get_family_id('TASKSTATS')
  File "/root/iotop-cgroups/iotop/genetlink.py", line 76, in get_family_id
    m = GeNlMessage.recv(self.conn)
  File "/root/iotop-cgroups/iotop/genetlink.py", line 56, in recv
    msg = conn.recv()
  File "/root/iotop-cgroups/iotop/netlink.py", line 255, in recv
    raise err
OSError: Netlink error: No such file or directory (2)

**Comment by sol-invictus** [comment]
I think this version of iotop should be used on the host system with the corresponding cgroups-id of the lxc container.

So your error is the same as in the original iotop:
https://forum.proxmox.com/threads/proxmox5-debian9-and-iotop-in-container-error.40838/

When I use this iotop version ( ./iotop.py -g -cgroups ) on the Proxmox 6 host I get the following error:
CONFIG_TASK_DELAY_ACCT not enabled in kernel, cannot determine SWAPIN and IO %

When I check /boot/config-[KERNEL-VERSION] CONFIG_TASK_DELAY_ACCT is enabled (CONFIG_TASK_DELAY_ACCT=y).

Also enabling it in the /etc/default/grub ( GRUB_CMDLINE_LINUX_DEFAULT="delayacct" ) like described here - http://blog.brocktice.com/2012/05/23/delayacct-and-iotop-in-ubuntu-10-04-lucid-lynx/ - changed nothing. What I'm doing wrong here?

Edit: I found out that ./iotop.py -g /lxc/[CONTAINER-ID] is not enough to list just the container IO. You have to exactly put the string like shown in CGROUP when running just ./iotop.py (sort by CGROUP reversed). In my case it was:

./iotop.py -g /lxc/1234/ns

So the error is just wrong and misleading.

**Comment by albertocavalcante** [comment]
@BrixSat  Were you able to get through it?

**Comment by BrixSat** [comment]
No. Sorry.
